_wandb:
    value:
        cli_version: 0.23.1
        e:
            8aet9keh68q9xsvhmb2gd6cyfx6bfgnh:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "510980853760"
                        used: "440191361024"
                email: nicholask@autogrowth.nl
                executable: C:\Users\nickk\Documents\Repo\SegmentationHub\.venv\scripts\python.exe
                git:
                    commit: 81688529ffaf808e9945d0d605be7258a5b43c6a
                    remote: https://github.com/nkolln/SegmentationHub.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-55b7e9d0-42b6-a1fc-4cc1-047dae1f2f55
                host: NickGaming
                memory:
                    total: "17023844352"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\nickk\Documents\Repo\SegmentationHub\train.py
                python: CPython 3.12.8
                root: C:\Users\nickk\Documents\Repo\SegmentationHub
                startedAt: "2025-12-24T18:17:37.201295Z"
                writerId: 8aet9keh68q9xsvhmb2gd6cyfx6bfgnh
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 49
                - 80
            "2":
                - 1
                - 49
                - 80
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.8
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
data:
    value:
        image_size: 512
        num_workers: 4
        root_dir: data
        test_split: 0.1
        train_split: 0.8
        val_split: 0.1
experiment_name:
    value: unet_baseline
logging:
    value:
        log_every_n_steps: 50
        output_dir: outputs
        save_checkpoint_every_n_epochs: 5
        use_wandb: true
loss:
    value:
        class_weights: null
        label_smoothing: 0.1
        type: cross_entropy
model:
    value:
        name: unet
        num_classes: 12
        pretrained: false
monitoring:
    value:
        gradient_log_frequency: 100
        track_gradients: true
        visualize_predictions_every_n_epochs: 5
project_name:
    value: paintable-surface-segmentation
training:
    value:
        batch_size: 8
        learning_rate: "6e-5"
        num_epochs: 100
        optimizer: adamw
        scheduler: polynomial
        seed: 42
        warmup_epochs: 10
        weight_decay: 0.01
